### ISSUE TITLE
starting on correctness proofs

### ISSUE THREAD

**Issue by afilinski** [Ginko-X/Streaming_NESL#25]
Let's establish value correctness (ignoring work/step, memory usage, scheduling, etc) first
[semantics.txt](https://github.com/Ginko-X/Streaming_NESL/files/1225124/semantics.txt)

**Comment by Ginko-X** [comment]
In the toy language, it's not clear (or maybe I forgot) that what we want pairs to do.
```
e ::= n | e1 + e2
         | x | let x = e1 in e2
         | (e1, e2) | fst(e) | snd(e)
```
As we don't have a type system, and only have **n** (integers) as values,  what I should deal with some exps like (1,2) + 3 ?

**Comment by afilinski** [comment]
Oh, maybe I wasn't clear. The intent was that you should figure out the definitions and theorems for the simple language (even without variables and let) first, and then gradually add each line of features. Supporting new features might require you to go back and revise some of the previous stuff, but that should still be easier than trying to solve the problem in full generality from the beginning. And in particular, the extension with pairs and projections will indeed require a (very simple) type system, as well as some generalizations in the translation and correctness proof.

I hadn't actually thought to allow arithmetic on non-int typed expressions at all, but on second thought, it would also make good sense as a further generalization to allow addition of arbitrary terms (component-wise), as long as they have exactly the same type. This would be rather similar to how ++ works in Snesl, where you can also only append values of the same (sequence) type. In particular, to properly generate code for expressions like x+y, you will need an inner induction on their (joint) type,

Incidentally, from the point of view of the inductive definition of the translation judgment/function, it may not be ideal to have an explicit "return r" instruction in the programs. I think it'll be easier to just say that a program p is a finite list of instructions s (to reserve the metavariale i for indices), and the information about which register holds the final value would be external to the program text itself -- much like it is in your Snesl compiler. That is, the translation judgment would return both a list of generated instructions and a register name, rather than just a program with a built-in return.

**Comment by Ginko-X** [comment]
A draft version of the correctness proof formalization for the toy language  if you are interested:
[toyversion.pdf](https://github.com/Ginko-X/Streaming_NESL/files/1236193/toyversion.pdf)

**Comment by afilinski** [comment]
Looks like a good start. A minor issue is that there should be some systematic mechanism in the translation judgments to ensure that the register names in the generated programs are non-overlapping (e.g., a counter keeping track of the next register number to use). 

But the major issue, of course, is how to actually prove the correctness theorems. And the first step here will be to find generalized formulations of the theorems so that they can be proved by induction (probably on the syntactic structure of e, at least for level 0 and 1).

**Comment by Ginko-X** [comment]
The minor issue makes sense. The major one:

> And the first step here will be to find generalized formulations of the theorems ...

I have some generalized theorems at the end (see below). But this is not what you are talking about? Or there are some other important theorems I need to prove as well? 
Also, it seems you are suggesting me to complete all the paper proof of this toy version language?
![image](https://user-images.githubusercontent.com/5687628/29489565-f4748f16-8523-11e7-81dc-5b23e66afaf7.png)

**Comment by afilinski** [comment]
Well, did you try doing the proofs for the toy language (at least for level 0 and 1) in detail? Even level 1 has only 4 cases, of which 2 (constants and variables) should be very simple. That was actually the main point of the exercise: to develop a model proof for the toy language, on which you could then confidently base the Snesl one. So I think this is well worth writing down carefully.

In particular, the theorem for level 0 looks too specialized to prove by induction, because it only talks about running the compiled code starting from an empty sigma, which will not be the case in general. The other two look more plausible, but I suspect they may still need some adjustments, once you look carefully at the proof cases. You may actually be able to prove them directly as stated, but then you'll probably need some simple additional lemmas for some of the proof cases. Note that how you resolve the minor issue (refining the translation judgement to ensure "freshness" of register names) may also influence the correctness theorems and/or their proofs.

**Comment by Ginko-X** [comment]
Ok, makes sense. 

Can we postpone this week's meeting a day or two? I got sick yesterday and may not work today. Wednesday or Friday would be fine with me.

**Comment by afilinski** [comment]
Sure. Should we tentatively say Wednesday at 14, with a possibility of moving to Friday at 14 if you are not quite ready? Get well soon!

**Comment by Ginko-X** [comment]
Yes, Wednesday 14  should be no problem. Thank you!

**Comment by Ginko-X** [comment]
I tried to fix the fresh register naming issue and added the proof for Level-0, if you're interested:
[toyversion2.pdf](https://github.com/Ginko-X/Streaming_NESL/files/1242865/toyversion2.pdf)
(I'll also try to write down the proof for Level-2 but may not have enough time to move them to the latex file before we meet tomorrow.)

**Comment by afilinski** [comment]
Looks much better, but there's still a significant outstanding issue, already at level 0. Basically, Lemma 1 clearly does not hold as stated, because there is nothing in the target language syntax or semantics to guarantee that previously assigned parts of the store sigma are not overwritten. (E.g., in sigma = [0 |-> 4, 1 |-> 5], we can execute the program "mov 0, 8" to get sigma' = [0 |-> 8, 1 |-> 5], which gives a counterexample to the lemma.)

I can see two ways of fixing this:
* Define a notion of "well-behaved" target programs, which ensures that the program does assign to registers that have previously been given a value. Then something like Lemma 1 would hold for well-behaved programs, but you'll also need to state and prove a separate lemma, saying that the translation of any source expression results in a well-behaved program. And in the statement of the main theorem, even if we know that p is well behaved, there needs to be some connection between r0 and sigma for the theorem to hold.

* Drop Lemma 1 as a separate proposition, and instead strengthen the main theorem to say not only that sigma'(r) = n, but also that for all r' < r0, sigma'(r') = sigma(r'). That is, the program p generated by the translation judgment is guaranteed to leave all registers below the "first free" one alone. Then that part of the IH will essentially give you what Lemma 1 does now, but of course there will be an additional proof obligation for each case.

**Comment by Ginko-X** [comment]
I added some proof cases for Level-2's correctness theorem and an auxiliary Lemma 2.
[toyversion3.pdf](https://github.com/Ginko-X/Streaming_NESL/files/1244825/toyversion3.pdf)
This Lemma 2 (maybe as well as the auxiliary theorem) has the same problem as you pointed out for Lemma 1, i.e., it should only hold for well-behaved target programs.

**Comment by afilinski** [comment]
I see you checked in a new version of the proof for the toy language. I'm not quite sure how finished it is meant to be, but there's still an unresolved issue with register-number generation. While the theorems for Level 0 look OK now, the problem enters in Level 1, and remains in Level 2; and it would probably affect the proof for Snesl in a similar way, so it should be fixed before you begin on that one.

First, Lemma 3 (and 6) clearly does not hold as stated, if you don't assume anything about the function delta: consider e = x, r0 = 0, and delta = [x |-> 100]; then you get r1 = 0 but r = 100, which does not validate r < r1.  I think it may be worth actually writing out the (quite simple) proof cases for this lemma, once you refine it, just to make absolutely sure everything works.

Second, and a bit more subtly, Theorem 4 (and 8) also doesn't hold if r0 is chosen so small that the compiled code p may overwrite registers already containing values corresponding to variables in rho. For example, consider e = x+1, rho = [x |-> 3], delta = [x |-> 0], sigma = [0 |-> 3], and r0 = 0. You'll probably need an additional assumption like "for all x in dom(rho). delta(x) < r0"; and then make sure that this relationship also holds whenever you apply the IH inside the proof, especially in the case for "let", where not only r0 but also rho and delta get modified.

**Comment by Ginko-X** [comment]
Yes, I also noticed the first issue, so I added some side condition under the translation judgment, which may be not formal enough.  And the second issue seems like a similar problem. 

![image](https://user-images.githubusercontent.com/5687628/29749914-9357adda-8b36-11e7-8365-dad6a0873362.png)

![image](https://user-images.githubusercontent.com/5687628/29749912-8694ab20-8b36-11e7-9fe3-773f08f7241f.png)

Now I think it may be better to use function style to describe the translation process for SNESL, so I don't need those auxiliary lemmas or conditions to take care of the freshness of register names.

**Comment by afilinski** [comment]
I think it may be slightly cleaner to express the extra condition in terms of the domain of rho (or Gamma for Level 2), rather than the codomain of delta, because in principle it doesn't matter if delta has some additional mappings for variables that can never be referenced in the compiled code, and therefore could safely be overwritten. (This probably makes no practical difference for the current toy language, but potentially it could get a little annoying when you add functions, because then you have to make sure to clean out any bindings from delta when they are no longer relevant.) But I think either formulation should work. I also think it would be preferable to leave the definition of the translation judgment itself alone, but add the extra condition to the lemmas and theorems about it. Note that the same condition on delta should suffice for both the lemma and the theorem (but it'll say slightly different things for Level 1 and Level 2).

I don't think the freshness issue would really go away with a functional formulation of the translation; you would still need more or less the same conditions and arguments to make sure everything works right. The only thing that might be different is that it would be _perhaps_ be easier to pack those arguments into suitable lemmas about the monad operations (return and >>=) used in the translation, so that the main proof becomes less repetitive. But right now it actually looks manageable enough also with the judgment-style translation. 

In any case, though, if you decide to use the functional style for the Snesl translation, I would strongly advise that you first work out the complete proof in that style for the toy language, at least for Level 1. I don't think there'll be any fundamental complications in scaling it up to Level 2, so it's probably OK to to skip the details of that, and go straight to (a subset of) Snesl.
